### ISSUE TITLE
ClientBuilder 

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/morpher-ws3-java-client#3]
Реализовать Builder pattern для создания клиента:

```java
ru.morpher.ws3.Client client = new ru.morpher.ws3.ClientBuilder()
.useUrl("http://...")
.useToken("token")
.useHttpClient(new OkHttpClient())
.build();
```

`useHttpClient` нужен для инъекции HTTP. клиента для тестов. Обычный пользователь может его не указывать.

Токен может не указываться.

URL по умолчанию https://ws3.morpher.ru, но может быть и другой.

**Comment by morlok1** [comment]
Добавлен ClientBuilder и заготовка MorpherClient.
Билдер покрыт простым тестом.
